import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api, fmtMoney } from '../lib/api';
import { PageHeader } from '../components/UI';
import { TIPOS, DEMANDA_STATUS } from './DemandaWizard';
import './collections.css';
import './business.css';
export default function DemandaDetalhe(){
 const {id}=useParams();const [d,setD]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [activity,setActivity]=useState({tipo:'nota',texto:''});const [doc,setDoc]=useState({tipo:'briefing',nome:'',url:''});
 const load=useCallback(()=>api(`/demandas/${id}`).then(setD),[id]);useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 async function add(e,path,body,reset){e.preventDefault();setBusy(true);setError('');try{await api(`/demandas/${id}/${path}`,{method:'POST',body:JSON.stringify(body)});reset();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!d)return <div className={error?'alert error':'panel'}>{error||'Carregando demanda...'}</div>;
 const blocks=[['Objetivo e regiões',[['Empresa',d.empresa.nome],['Tipo',TIPOS[d.tipo]],['Finalidade',d.finalidade==='expansao_redes'?'Expansão de redes':d.finalidade],['Objetivo',d.objetivo],['Unidades',d.unidades],['Prazo',d.prazo],['Regiões',d.regioesInteresse],['Perfil',d.perfilImovel]]],['Diretrizes técnicas',[['Área mínima / máxima',`${d.areaMinima??'—'} / ${d.areaMaxima??'—'} m²`],['Frente mínima',d.frenteMinima],['Pé-direito mínimo',d.peDireitoMinimo],['Vagas mínimas',d.vagasMinimas],['Acessibilidade',d.acessibilidade],['Exigências',d.exigencias],['Restrições',d.restricoes]]],['Condições comerciais',[['Aluguel mínimo / máximo',`${fmtMoney(d.aluguelMinimo)} / ${fmtMoney(d.aluguelMaximo)}`],['Compra mínima / máxima',`${fmtMoney(d.compraMinima)} / ${fmtMoney(d.compraMaxima)}`],['CDU',fmtMoney(d.cdu)],['Luvas',fmtMoney(d.luvas)],['Passagem de ponto',fmtMoney(d.valorPonto)],['Carência (meses)',d.carenciaMeses],['Investimento previsto',fmtMoney(d.investimento)]]],['Acompanhamento',[['Status',DEMANDA_STATUS[d.status]],['Responsável empresa',d.responsavelEmpresa],['Consultor',d.consultor],['Início',d.inicioEm],['Próxima ação',d.proximaAcao],['Data',d.proximaAcaoEm],['Observações',d.observacoes]]]];
 return <div className="collection-page"><PageHeader eyebrow="DEMANDA DE EXPANSÃO" title={d.titulo} description={d.empresa.nome} actions={<Link className="btn btn-gold" to={`/demandas/${id}/editar`}>Editar demanda</Link>}/>{error&&<div className="alert error" role="alert">{error}</div>}<div className="business-grid">{blocks.map(([title,items])=><section className="panel business-panel" key={title}><h2>{title}</h2><dl>{items.map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v??'Não informado'}</dd></div>)}</dl></section>)}</div>
 <section className="panel business-panel"><div className="collection-section-head"><div><h2>Operações vinculadas</h2><p>Imóveis apresentados, visitas, propostas e negociações.</p></div><Link className="btn btn-primary" to={`/oportunidades?demandaId=${id}`}>Relacionamentos comerciais</Link></div>{d.oportunidades.length?d.oportunidades.map(o=><p key={o.id}><Link to={`/imoveis/${o.imovelId}`}>{o.imovel.codigo} · {o.imovel.endereco}</Link> — {o.etapa}</p>):<p>Nenhum imóvel apresentado ainda.</p>}</section>
 <div className="business-grid"><section className="panel business-panel"><h2>Histórico de acompanhamento</h2><form onSubmit={e=>add(e,'atividades',activity,()=>setActivity({tipo:'nota',texto:''}))} className="business-form"><label>Tipo<select value={activity.tipo} onChange={e=>setActivity({...activity,tipo:e.target.value})}>{['nota','contato','visita','proposta','status'].map(t=><option key={t}>{t}</option>)}</select></label><label>Registro<textarea required value={activity.texto} onChange={e=>setActivity({...activity,texto:e.target.value})}/></label><button className="btn btn-primary" disabled={busy}>Registrar atividade</button></form>{d.atividades.map(a=><article className="business-entry" key={a.id}><small>{new Date(a.criadoEm).toLocaleString('pt-BR')} · {a.tipo}</small><p>{a.texto}</p></article>)}</section>
 <section className="panel business-panel"><h2>Documentos e contrato</h2><p>Vincule documentos do Drive ou de outro repositório da empresa.</p><form className="business-form" onSubmit={e=>add(e,'documentos',doc,()=>setDoc({tipo:'briefing',nome:'',url:''}))}><label>Tipo<select value={doc.tipo} onChange={e=>setDoc({...doc,tipo:e.target.value})}>{['briefing','contrato','proposta','anexo'].map(t=><option key={t}>{t}</option>)}</select></label><label>Nome<input required value={doc.nome} onChange={e=>setDoc({...doc,nome:e.target.value})}/></label><label>Link<input type="url" required value={doc.url} onChange={e=>setDoc({...doc,url:e.target.value})}/></label><button className="btn btn-primary" disabled={busy}>Vincular documento</button></form>{d.documentos.map(doc=><p className="business-entry" key={doc.id}><a target="_blank" rel="noopener noreferrer" href={doc.url}>{doc.nome} ↗</a> · {doc.tipo}</p>)}</section></div>
 <section className="panel business-panel"><div className="collection-section-head"><h2>Propostas de serviços</h2><Link className="btn btn-primary" to={`/propostas?demandaId=${id}`}>Gerenciar propostas</Link></div>{d.propostas.map(p=><p key={p.id}>{p.numero} · {p.data?p.data.split('-').reverse().join('/'):'sem data'} · {p.status}</p>)}</section></div>;
}
