import { useCallback, useEffect, useMemo, useState } from 'react';
import { BookOpen, PencilSimple, Plus } from '@phosphor-icons/react';
import { api } from '../lib/api';
import { PageHeader } from '../components/UI';
import Modal from '../components/Modal';
import BusinessFields from '../components/BusinessFields';
import './collections.css';import './business.css';
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const fields=[['termo','Termo ou sigla','text',true],['nomeExtenso','Nome por extenso / tradução'],['categoria','Categoria','text',true],['significado','Significado em português','textarea',true],['exemplo','Exemplo de aplicação','textarea'],['relacionados','Termos relacionados (separados por vírgula)'],['aliases','Outras grafias para busca'],['fonte','Fonte / referência'],['revisadoEm','Data de revisão','date']];
const formulas=[['Ticket médio','Receita de vendas ÷ número de transações no mesmo período.'],['ROI simples','Ganho líquido ÷ capital aplicado × 100. Informar o período.'],['Payback simples','Com fluxo constante: investimento ÷ fluxo líquido por período.'],['Cap rate','NOI anual ÷ preço do imóvel × 100. Aluguel bruto não é NOI.'],['Vacância física','Área locável desocupada ÷ área locável total × 100.'],['Margem de contribuição','Receita − custos e despesas variáveis.'],['Custo básico de ocupação','Aluguel + IPTU + condomínio, na mesma periodicidade.']];
export default function Glossario(){
 const [terms,setTerms]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [q,setQ]=useState('');const [category,setCategory]=useState('');const [form,setForm]=useState(null);const [formError,setFormError]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(()=>api('/glossario').then(setTerms),[]);useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[load]);
 const categories=useMemo(()=>[...new Set(terms.map(t=>t.categoria))].sort((a,b)=>a.localeCompare(b,'pt-BR')),[terms]);
 const filtered=useMemo(()=>terms.filter(t=>(!category||t.categoria===category)&&normalize([t.termo,t.nomeExtenso,t.significado,t.exemplo,t.aliases,t.relacionados].join(' ')).includes(normalize(q))).sort((a,b)=>a.termo.localeCompare(b.termo,'pt-BR')),[terms,q,category]);
 async function save(e){e.preventDefault();setBusy(true);setFormError('');try{await api(form.id?`/glossario/${form.id}`:'/glossario',{method:form.id?'PUT':'POST',body:JSON.stringify(form)});setForm(null);await load();}catch(e){setFormError(e.message);}finally{setBusy(false);}}
 return <div className="collection-page"><PageHeader eyebrow="CONHECIMENTO" title="Glossário de Negócios, Varejo & Real Estate" description="Siglas, expressões e conceitos para a prospecção, a expansão de redes e as operações imobiliárias." actions={<button className="btn btn-gold" onClick={()=>{setForm({revisadoEm:new Date().toLocaleDateString('en-CA')});setFormError('');}}><Plus size={18}/> Novo termo</button>}/>
 <div className="glossary-tools"><input aria-label="Buscar termo" placeholder="Buscar termo, sigla, nome por extenso ou significado..." value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Categoria" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{categories.map(c=><option key={c}>{c}</option>)}</select>{(q||category)&&<button className="btn btn-ghost" onClick={()=>{setQ('');setCategory('');}}>Limpar filtros</button>}</div>
 <p>{loading?'Carregando glossário...':`${filtered.length} de ${terms.length} termos · Ordem alfabética`}</p>{error&&<div role="alert" className="alert error">{error}<button className="btn btn-ghost" onClick={()=>{setError('');load().catch(e=>setError(e.message));}}>Tentar novamente</button></div>}
 <div className="business-grid">{filtered.map(t=><article className="panel glossary-card" key={t.id}><div className="collection-section-head"><span className="collection-tag">{t.categoria}</span><button className="icon-button" aria-label={`Editar ${t.termo}`} onClick={()=>{setForm(t);setFormError('');}}><PencilSimple size={18}/></button></div><h2>{t.termo}</h2><strong>{t.nomeExtenso}</strong><p>{t.significado}</p>{t.exemplo&&<p className="glossary-example"><strong>Exemplo: </strong>{t.exemplo}</p>}{t.relacionados&&<div className="glossary-related">{t.relacionados.split(',').map(s=><button key={s} onClick={()=>{setQ(s.trim());setCategory('');window.scrollTo({top:0,behavior:'smooth'});}}>{s.trim()}</button>)}</div>}<footer>{t.fonte||'Fonte não informada'}<br/>Revisão: {t.revisadoEm?t.revisadoEm.split('-').reverse().join('/'):'Não informada'}</footer></article>)}</div>
 {!loading&&!error&&!filtered.length&&<section className="panel business-panel"><BookOpen size={32}/><h2>Nenhum termo encontrado</h2><p>Experimente outra busca ou categoria.</p></section>}
 <section className="panel business-panel"><h2>Fórmulas e distinções importantes</h2><dl>{formulas.map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v}</dd></div>)}</dl><p>Nem todo desembolso inicial é CAPEX. Separe obras e equipamentos, estoque inicial, capital de giro e pagamentos pelo ponto. O custo de ocupação é apenas parte do OPEX.</p><p>Expansão de redes é a finalidade da demanda. Locação, passagem de ponto e venda do ativo são modalidades que podem viabilizar essa expansão. Registre CDU, luvas e passagem de ponto separadamente.</p></section>
 {form&&<Modal wide title={form.id?'Editar termo':'Novo termo'} onClose={()=>!busy&&setForm(null)} footer={<><button className="btn btn-ghost" disabled={busy} onClick={()=>setForm(null)}>Cancelar</button><button className="btn btn-primary" form="glossario-form" type="submit" disabled={busy}>{busy?'Salvando...':'Salvar termo'}</button></>}><form id="glossario-form" onSubmit={save}>{formError&&<div className="alert error" role="alert">{formError}</div>}<BusinessFields fields={fields} form={form} onChange={(k,v)=>setForm(f=>({...f,[k]:v}))}/></form></Modal>}</div>;
}
