import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Buildings, CircleNotch, EnvelopeSimple, Eye, EyeSlash, LockKey, ShieldCheck } from '@phosphor-icons/react';

export default function Login() {
  const [email, setEmail] = useState(''); const [senha, setSenha] = useState(''); const [err, setErr] = useState(''); const [loading, setLoading] = useState(false); const [showPassword, setShowPassword] = useState(false); const [help, setHelp] = useState(false); const nav = useNavigate();
  async function submit(e) {
    e.preventDefault(); if (loading) return; setLoading(true); setErr('');
    try {
      const res = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: email.trim(), senha }) });
      const result = await res.json(); if (!res.ok) throw new Error(result.error || 'Não foi possível entrar. Confira seus dados.');
      localStorage.setItem('pb_token', result.token); localStorage.setItem('pb_user', JSON.stringify(result.usuario)); nav('/', { replace: true });
    } catch (error) { setErr(error.message === 'Failed to fetch' ? 'Não foi possível conectar. Tente novamente em instantes.' : error.message); } finally { setLoading(false); }
  }
  return <div className="login-page"><section className="login-brand-panel" aria-label="Prospecção Brasil"><a href="https://prospeccaobrasil.com.br" className="login-logo"><img src="/images/logo-wide.png" alt="Prospecção Brasil" /></a><div className="login-brand-content"><div className="eyebrow"><span />INTELIGÊNCIA IMOBILIÁRIA</div><h1>Grandes negócios.<br /><em>Novas possibilidades.</em></h1><p>O endereço certo conecta marcas,<br />pessoas e oportunidades.</p><figure><img src="/images/brand-architecture.png" alt="Maquete conceitual de um empreendimento comercial" /><figcaption><Buildings size={16} /> VISÃO ESTRATÉGICA. EXPANSÃO COM PROPÓSITO.</figcaption></figure></div><div className="login-brand-footer"><span>RETAIL & REAL ESTATE</span><span>RIO DE JANEIRO · BRASIL</span></div></section>
    <section className="login-access"><a className="login-back" href="https://prospeccaobrasil.com.br"><ArrowLeft size={16} />Voltar ao site</a><div className="login-form-wrap"><span className="login-lock"><LockKey size={25} weight="duotone" /></span><div className="eyebrow">SEU ESPAÇO DE TRABALHO</div><h2>Bem-vindo de volta.</h2><p className="login-description">Entre para acompanhar sua operação e<br className="desktop-only" /> transformar conexões em bons negócios.</p>
      <form onSubmit={submit} className="login-form">{err && <div className="alert error" role="alert">{err}</div>}<div className="field"><label htmlFor="login-email">E-mail profissional</label><div className="input-icon"><EnvelopeSimple size={19} /><input id="login-email" type="email" autoComplete="username" placeholder="voce@prospeccaobrasil.com.br" value={email} onChange={e => setEmail(e.target.value)} required /></div></div><div className="field"><div className="login-label-row"><label htmlFor="login-password">Senha</label><button type="button" className="text-button" onClick={() => setHelp(!help)}>Esqueceu a senha?</button></div><div className="input-icon"><LockKey size={19} /><input id="login-password" type={showPassword ? 'text' : 'password'} autoComplete="current-password" placeholder="Digite sua senha" value={senha} onChange={e => setSenha(e.target.value)} required /><button type="button" aria-label={showPassword ? 'Ocultar senha' : 'Mostrar senha'} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeSlash size={19} /> : <Eye size={19} />}</button></div></div>{help && <div className="alert" role="status">Para recuperar o acesso, entre em contato com o administrador da sua equipe.</div>}<button type="submit" className="btn btn-primary login-submit" disabled={loading}>{loading ? <><CircleNotch size={20} className="spin" />Entrando…</> : <>Acessar plataforma <ArrowRight size={19} /></>}</button></form>
      <div className="login-security"><ShieldCheck size={17} /><span>Acesso seguro e exclusivo para nossa equipe.</span></div></div><footer className="login-footer">© {new Date().getFullYear()} Prospecção Brasil <span>Todos os direitos reservados.</span></footer></section>
  </div>;
}
