import { useEffect, useState } from 'react';import { useSearchParams } from 'react-router-dom';
import { api, fmtMoney } from '../lib/api';import { PageHeader } from '../components/UI';import DataTable from '../components/DataTable';import Modal from '../components/Modal';import BusinessFields from '../components/BusinessFields';import './collections.css';
const STATUS={rascunho:'Rascunho',enviada:'Enviada',aceita:'Aceita',recusada:'Recusada'};
const fields=[['demandaId','Demanda / empresa','select',true],['titulo','Título','text',true],['escopo','Escopo dos serviços','textarea',true],['honorarios','Honorários (R$)','number'],['prazo','Prazos e entregas'],['condicoes','Condições comerciais','textarea'],['status','Status','select',true]];
export default function Propostas(){const [search]=useSearchParams();const [list,setList]=useState([]);const [demandas,setDemandas]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [form,setForm]=useState(null);const [busy,setBusy]=useState(false);const [formError,setFormError]=useState('');
 async function load(){const [p,d]=await Promise.all([api('/propostas'),api('/demandas')]);setList(p);setDemandas(d);}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function save(e){e.preventDefault();setBusy(true);setFormError('');try{await api(form.id?`/propostas/${form.id}`:'/propostas',{method:form.id?'PUT':'POST',body:JSON.stringify(form)});setForm(null);await load();}catch(e){setFormError(e.message);}finally{setBusy(false);}}
 const columns=[{accessorKey:'titulo',header:'Proposta',cell:({row:{original:p}})=><button className="btn btn-ghost" onClick={()=>{setForm(p);setFormError('');}}>{p.titulo}</button>},{id:'demanda',header:'Empresa / demanda',accessorFn:p=>`${p.demanda.empresa.nome} · ${p.demanda.titulo}`},{accessorKey:'escopo',header:'Escopo'},{accessorKey:'honorarios',header:'Honorários',cell:({getValue})=>fmtMoney(getValue())},{accessorKey:'prazo',header:'Prazo'},{accessorKey:'status',header:'Status',cell:({getValue})=>STATUS[getValue()]}];
 return <div className="collection-page"><PageHeader eyebrow="GESTÃO DE EXPANSÃO" title="Propostas Comerciais" description="Escopo, honorários, prazos e condições dos serviços prestados pela Prospecção Brasil." actions={<button className="btn btn-gold" disabled={loading||!!error} onClick={()=>{setForm({status:'rascunho',demandaId:search.get('demandaId')||''});setFormError('');}}>Nova proposta</button>}/><section className="panel collection-panel"><DataTable columns={columns} data={list.filter(p=>!search.get('demandaId')||String(p.demandaId)===search.get('demandaId'))} loading={loading} error={error} searchPlaceholder="Buscar proposta, empresa ou demanda..." emptyTitle="Nenhuma proposta de serviço" exportName="propostas.csv"/></section>{form&&<Modal wide title={form.id?'Editar proposta':'Nova proposta de serviço'} onClose={()=>!busy&&setForm(null)} footer={<><button className="btn btn-ghost" disabled={busy} onClick={()=>setForm(null)}>Cancelar</button><button className="btn btn-primary" form="proposta-form" type="submit" disabled={busy||!demandas.length}>{busy?'Salvando...':'Salvar proposta'}</button></>}><form id="proposta-form" onSubmit={save}>{formError&&<div className="alert error" role="alert">{formError}</div>}{!demandas.length&&<p>Cadastre uma demanda antes de criar a proposta de serviço.</p>}<BusinessFields fields={fields} form={form} options={{demandaId:demandas.map(d=>[d.id,`${d.empresa.nome} · ${d.titulo}`]),status:Object.entries(STATUS)}} onChange={(k,v)=>setForm(f=>({...f,[k]:v}))}/></form></Modal>}</div>;
}
