-- AlterTable
ALTER TABLE "empresas" ADD COLUMN "endereco" TEXT;
ALTER TABLE "empresas" ADD COLUMN "razao_social" TEXT;

-- AlterTable
ALTER TABLE "imoveis" ADD COLUMN "acessibilidade" TEXT;
ALTER TABLE "imoveis" ADD COLUMN "carencia_meses" INTEGER;
ALTER TABLE "imoveis" ADD COLUMN "infraestrutura" TEXT;
ALTER TABLE "imoveis" ADD COLUMN "luvas" DECIMAL;
ALTER TABLE "imoveis" ADD COLUMN "restricoes_uso" TEXT;
ALTER TABLE "imoveis" ADD COLUMN "vagas" INTEGER;
ALTER TABLE "imoveis" ADD COLUMN "valor_ponto" DECIMAL;

-- CreateTable
CREATE TABLE "demandas" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "empresa_id" INTEGER NOT NULL,
    "titulo" TEXT NOT NULL,
    "tipo" TEXT NOT NULL DEFAULT 'locacao',
    "finalidade" TEXT NOT NULL DEFAULT 'expansao_redes',
    "objetivo" TEXT,
    "unidades" INTEGER,
    "prazo" TEXT,
    "regioes_interesse" TEXT,
    "perfil_imovel" TEXT,
    "area_minima" DECIMAL,
    "area_maxima" DECIMAL,
    "frente_minima" DECIMAL,
    "pe_direito_minimo" DECIMAL,
    "vagas_minimas" INTEGER,
    "acessibilidade" TEXT,
    "exigencias" TEXT,
    "aluguel_minimo" DECIMAL,
    "aluguel_maximo" DECIMAL,
    "compra_minima" DECIMAL,
    "compra_maxima" DECIMAL,
    "cdu" DECIMAL,
    "luvas" DECIMAL,
    "valor_ponto" DECIMAL,
    "carencia_meses" INTEGER,
    "investimento" DECIMAL,
    "restricoes" TEXT,
    "responsavel_empresa" TEXT,
    "consultor" TEXT,
    "inicio_em" TEXT,
    "proxima_acao" TEXT,
    "proxima_acao_em" TEXT,
    "status" TEXT NOT NULL DEFAULT 'aberta',
    "observacoes" TEXT,
    "criado_em" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "atualizado_em" DATETIME NOT NULL,
    CONSTRAINT "demandas_empresa_id_fkey" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "demanda_documentos" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "demanda_id" INTEGER NOT NULL,
    "tipo" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "criado_em" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "demanda_documentos_demanda_id_fkey" FOREIGN KEY ("demanda_id") REFERENCES "demandas" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "demanda_atividades" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "demanda_id" INTEGER NOT NULL,
    "tipo" TEXT NOT NULL DEFAULT 'nota',
    "texto" TEXT NOT NULL,
    "criado_em" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "demanda_atividades_demanda_id_fkey" FOREIGN KEY ("demanda_id") REFERENCES "demandas" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "propostas_servico" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "demanda_id" INTEGER NOT NULL,
    "titulo" TEXT NOT NULL,
    "escopo" TEXT NOT NULL,
    "honorarios" DECIMAL,
    "prazo" TEXT,
    "condicoes" TEXT,
    "status" TEXT NOT NULL DEFAULT 'rascunho',
    "criado_em" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "atualizado_em" DATETIME NOT NULL,
    CONSTRAINT "propostas_servico_demanda_id_fkey" FOREIGN KEY ("demanda_id") REFERENCES "demandas" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "glossario_termos" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "termo" TEXT NOT NULL,
    "nome_extenso" TEXT,
    "categoria" TEXT NOT NULL,
    "significado" TEXT NOT NULL,
    "exemplo" TEXT,
    "aliases" TEXT,
    "relacionados" TEXT,
    "fonte" TEXT,
    "revisado_em" TEXT
);

-- CreateTable
CREATE TABLE "benchmarks_locacao" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "local" TEXT NOT NULL,
    "municipio" TEXT NOT NULL,
    "corredor" TEXT NOT NULL,
    "valor_m2" DECIMAL NOT NULL,
    "minimo_m2" DECIMAL NOT NULL,
    "maximo_m2" DECIMAL NOT NULL,
    "classe" TEXT NOT NULL,
    "fonte" TEXT NOT NULL
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_oportunidades" (
    "demanda_id" INTEGER,
    "finalidade" TEXT,
    "proxima_acao" TEXT,
    "proxima_acao_em" TEXT,
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "imovel_id" INTEGER NOT NULL,
    "empresa_id" INTEGER NOT NULL,
    "etapa" TEXT NOT NULL DEFAULT 'apresentado',
    "modalidade" TEXT,
    "observacao" TEXT,
    "criado_em" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "atualizado_em" DATETIME NOT NULL,
    CONSTRAINT "oportunidades_demanda_id_fkey" FOREIGN KEY ("demanda_id") REFERENCES "demandas" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "oportunidades_imovel_id_fkey" FOREIGN KEY ("imovel_id") REFERENCES "imoveis" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "oportunidades_empresa_id_fkey" FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_oportunidades" ("atualizado_em", "criado_em", "empresa_id", "etapa", "id", "imovel_id", "modalidade", "observacao") SELECT "atualizado_em", "criado_em", "empresa_id", "etapa", "id", "imovel_id", "modalidade", "observacao" FROM "oportunidades";
DROP TABLE "oportunidades";
ALTER TABLE "new_oportunidades" RENAME TO "oportunidades";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE INDEX "demandas_empresa_id_idx" ON "demandas"("empresa_id");

-- CreateIndex
CREATE UNIQUE INDEX "glossario_termos_termo_key" ON "glossario_termos"("termo");

-- CreateIndex
CREATE UNIQUE INDEX "benchmarks_locacao_local_key" ON "benchmarks_locacao"("local");


INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('B2B', 'Business to Business', 'Negócios e relações comerciais', 'Relação comercial em que uma empresa vende produtos ou presta serviços a outra empresa.', 'Consultoria de expansão prestada a uma rede de farmácias.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('B2C', 'Business to Consumer', 'Negócios e relações comerciais', 'Venda de produtos ou serviços de uma empresa diretamente ao consumidor final.', 'Uma farmácia vende um produto ao cliente na loja.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('B2B2C', 'Business to Business to Consumer', 'Negócios e relações comerciais', 'Modelo em que uma empresa alcança o consumidor final por meio de outra empresa parceira.', 'Fabricante oferece produtos ao consumidor por uma plataforma varejista.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('D2C', 'Direct to Consumer', 'Negócios e relações comerciais', 'Venda direta da marca ou fabricante ao consumidor, sem um revendedor intermediário.', 'Marca comercializa seus produtos em loja própria.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Joint venture', 'Empreendimento conjunto', 'Negócios e relações comerciais', 'Arranjo em que empresas unem recursos para um projeto ou negócio, com responsabilidades e resultados definidos.', 'Duas empresas desenvolvem juntas um empreendimento comercial.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Stakeholder', 'Parte interessada', 'Negócios e relações comerciais', 'Pessoa ou organização que influencia ou é afetada por um negócio ou projeto.', 'Proprietário, locatário, investidor e comunidade do entorno.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Networking', 'Rede de contatos', 'Negócios e relações comerciais', 'Construção e manutenção de relações profissionais que podem gerar informações, indicações e negócios.', 'Relacionamento com responsáveis pela expansão de redes.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Benchmarking', 'Comparação de práticas', 'Negócios e relações comerciais', 'Análise de referências e práticas de outras empresas para identificar melhorias e oportunidades.', 'Comparar formatos de loja e padrões de atendimento.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Core business', 'Atividade principal', 'Negócios e relações comerciais', 'Atividade central que define o negócio e concentra sua geração de valor.', 'O core business de uma farmácia é seu varejo de saúde.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('M&A', 'Mergers and Acquisitions', 'Negócios e relações comerciais', 'Fusões e aquisições: operações de combinação ou compra de empresas e participações societárias.', 'Um grupo adquire uma rede regional de lojas.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Retail', 'Varejo', 'Varejo, formatos e canais', 'Comercialização de produtos e serviços ao consumidor final, em canais físicos ou digitais.', 'Rede que opera lojas de utilidades domésticas.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Atacado', 'Venda em escala', 'Varejo, formatos e canais', 'Comercialização geralmente voltada a revendedores ou compradores empresariais, com condições próprias de volume.', 'Distribuidor abastece supermercados e pequenos comércios.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Atacarejo', 'Atacado e varejo', 'Varejo, formatos e canais', 'Formato que combina atendimento a consumidores e compradores comerciais, frequentemente com preços por quantidade.', 'Loja atende famílias e comerciantes no mesmo espaço.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Franquia', 'Franchising', 'Varejo, formatos e canais', 'Modelo de negócio que permite operar uma marca e seu sistema empresarial conforme condições contratuais.', 'Empreendedor abre uma unidade de uma rede franqueadora.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Flagship', 'Loja de referência', 'Varejo, formatos e canais', 'Unidade que expressa a identidade da marca e pode apresentar experiências, serviços ou portfólio ampliado.', 'Loja emblemática da rede em uma avenida de destaque.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Loja âncora', 'Operação de atração', 'Varejo, formatos e canais', 'Estabelecimento com capacidade de atrair público e contribuir para o movimento de um empreendimento.', 'Supermercado que atrai visitantes a um centro comercial.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Mix de lojas', 'Composição de operações', 'Varejo, formatos e canais', 'Combinação de segmentos, marcas e serviços presentes em um empreendimento ou polo comercial.', 'Farmácia, alimentação, academia e serviços no mesmo conjunto.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Omnichannel', 'Integração de canais', 'Varejo, formatos e canais', 'Estratégia que conecta canais de venda e atendimento para dar continuidade à experiência do cliente.', 'Comprar no site e retirar na loja com informações integradas.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — Sebrae — Omnichannel', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('E-commerce', 'Comércio eletrônico', 'Varejo, formatos e canais', 'Venda de produtos ou serviços realizada por meios digitais.', 'Uma rede vende também por sua loja virtual.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Marketplace', 'Plataforma de vendedores', 'Varejo, formatos e canais', 'Ambiente que reúne ofertas de diferentes vendedores e intermedeia operações conforme suas regras.', 'Varejista anuncia produtos em uma plataforma de terceiros.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Expansão de rede', 'Crescimento da operação', 'Expansão e implantação de operações', 'Ampliação da presença de uma marca por novas unidades, territórios ou formatos comerciais.', 'Rede procura imóveis para abrir lojas em novos bairros.', '', 'Site selection, Pipeline de expansão, Rollout', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Site selection', 'Escolha de localização', 'Expansão e implantação de operações', 'Processo de selecionar um imóvel ou local considerando mercado, operação, custos e requisitos da empresa.', 'Avaliar três lojas para instalar uma nova farmácia.', '', 'Trade area, Geomarketing, Footfall', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Pipeline de expansão', 'Carteira de projetos', 'Expansão e implantação de operações', 'Conjunto de oportunidades e projetos de novas unidades, organizado por estágio de desenvolvimento.', 'Imóveis em análise, visita, negociação e implantação.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Rollout', 'Implantação em sequência', 'Expansão e implantação de operações', 'Execução de um plano de abertura ou padronização de unidades em diferentes locais.', 'Implantar dez lojas seguindo o mesmo projeto e cronograma.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('QSR', 'Quick Service Restaurant', 'Expansão e implantação de operações', 'Restaurante de serviço rápido, com processos padronizados e foco em agilidade de atendimento.', 'Operação de alimentação com pedido e entrega rápidos.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Drive-thru', 'Atendimento no veículo', 'Expansão e implantação de operações', 'Formato em que o cliente é atendido sem sair do veículo, em percurso próprio.', 'Restaurante com pista para pedido, pagamento e retirada.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Strip mall', 'Centro comercial linear', 'Expansão e implantação de operações', 'Conjunto de lojas geralmente disposto em faixa, com acessos voltados ao exterior e estacionamento próximo.', 'Lojas de conveniência e serviços voltadas para um estacionamento.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Pop-up store', 'Loja temporária', 'Expansão e implantação de operações', 'Unidade aberta por período limitado para testar mercado, promover uma marca ou atender uma temporada.', 'Loja sazonal instalada durante o verão.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Shop-in-shop', 'Loja dentro de outra loja', 'Expansão e implantação de operações', 'Espaço de uma marca ou operação instalado dentro de um estabelecimento maior.', 'Área de uma marca de cosméticos dentro de uma loja.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Fit-out', 'Adequação interna', 'Expansão e implantação de operações', 'Obras e instalações para preparar o espaço para a operação do ocupante.', 'Instalar iluminação, balcões e infraestrutura da nova loja.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Branding', 'Gestão da marca', 'Marketing, marcas e experiência', 'Construção e gestão da identidade, percepção e posicionamento de uma marca.', 'Definir linguagem visual e experiência das unidades da rede.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — Sebrae SC; Shopify — Co-branding e co-marketing', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Co-branding', 'Associação de marcas', 'Marketing, marcas e experiência', 'Parceria em que duas ou mais marcas associam suas identidades em produto, serviço ou experiência conjunta.', 'Cafeteria e marca de chocolate lançam uma bebida conjunta.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — Sebrae SC; Shopify — Co-branding e co-marketing', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Co-marketing', 'Marketing conjunto', 'Marketing, marcas e experiência', 'Ação promocional realizada por empresas parceiras para alcançar públicos e objetivos compartilhados.', 'Duas empresas divulgam juntas um evento para seus clientes.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — Sebrae SC; Shopify — Co-branding e co-marketing', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Rebranding', 'Reformulação da marca', 'Marketing, marcas e experiência', 'Mudança planejada na identidade ou no posicionamento de uma marca.', 'Rede atualiza nome, identidade visual e comunicação.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Posicionamento', 'Lugar da marca no mercado', 'Marketing, marcas e experiência', 'Proposta de valor e percepção que a empresa busca construir para determinado público.', 'Posicionar uma rede como referência em conveniência.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Público-alvo', 'Grupo de clientes', 'Marketing, marcas e experiência', 'Conjunto de pessoas ou empresas a que se destina uma oferta, definido por características relevantes.', 'Moradores e trabalhadores do entorno de uma loja.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Persona', 'Perfil representativo', 'Marketing, marcas e experiência', 'Representação de um cliente típico baseada em dados e pesquisa, usada para orientar decisões.', 'Perfil de consumidor que procura compras rápidas após o trabalho.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Customer journey', 'Jornada do cliente', 'Marketing, marcas e experiência', 'Etapas e interações vividas pelo cliente desde o primeiro contato até a compra e o relacionamento posterior.', 'Pesquisar, visitar a loja, comprar e receber atendimento pós-venda.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('CX', 'Customer Experience', 'Marketing, marcas e experiência', 'Experiência do cliente: percepção formada pelo conjunto de contatos com a empresa.', 'Avaliar facilidade de compra, atendimento e entrega.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Visual merchandising', 'Apresentação comercial', 'Marketing, marcas e experiência', 'Organização visual de produtos e ambientes para facilitar a compra e valorizar a oferta.', 'Planejar vitrines, sinalização e exposição de categorias.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Lead', 'Contato potencial', 'Vendas e relacionamento comercial', 'Pessoa ou empresa identificada como possível cliente, ainda sujeita à qualificação.', 'Rede que demonstrou interesse em receber oportunidades.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Prospect', 'Potencial cliente em prospecção', 'Vendas e relacionamento comercial', 'Contato trabalhado comercialmente; o grau de qualificação pode variar conforme a empresa.', 'Empresa abordada para avaliar sua demanda por imóveis.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('CRM', 'Customer Relationship Management', 'Vendas e relacionamento comercial', 'Gestão do relacionamento com clientes e, por extensão, o sistema usado para registrar contatos e negócios.', 'Cadastrar empresa, histórico, visitas, propostas e retornos.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Funil de vendas', 'Etapas de conversão', 'Vendas e relacionamento comercial', 'Modelo que organiza a evolução do contato inicial até a contratação.', 'Contato, qualificação, apresentação, proposta e fechamento.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Pipeline comercial', 'Carteira de oportunidades', 'Vendas e relacionamento comercial', 'Visão das negociações em andamento, com etapas, responsáveis e previsão de evolução.', 'Lista de locações e vendas em negociação.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Follow-up', 'Acompanhamento', 'Vendas e relacionamento comercial', 'Contato ou ação de continuidade para obter retorno e avançar uma negociação.', 'Retomar o contato após a visita ao imóvel.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Pitch', 'Apresentação breve', 'Vendas e relacionamento comercial', 'Exposição objetiva de uma proposta de valor ou oportunidade.', 'Apresentar em poucos minutos a aderência de um ponto à rede.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Conversão', 'Avanço ou resultado', 'Vendas e relacionamento comercial', 'Passagem de um contato ou oportunidade para um resultado definido, como visita ou contrato.', 'Medir quantas propostas resultaram em contratos.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Cross-selling', 'Venda complementar', 'Vendas e relacionamento comercial', 'Oferta de produtos ou serviços relacionados à compra ou demanda principal.', 'Oferecer estudo de mercado junto à prospecção de imóveis.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Upselling', 'Ampliação da oferta', 'Vendas e relacionamento comercial', 'Oferta de uma solução mais completa ou de maior valor para a mesma necessidade.', 'Ampliar um levantamento pontual para um estudo completo de expansão.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('CAPEX', 'Capital Expenditure', 'Finanças, custos e retorno', 'Investimentos em ativos ou melhorias de benefício duradouro, como equipamentos e determinadas obras.', 'Comprar equipamentos e executar adequações permanentes da loja.', '', 'OPEX, Fit-out, Payback', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — B3 — CAPEX e OPEX', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('OPEX', 'Operating Expenditure', 'Finanças, custos e retorno', 'Custos e despesas ligados à manutenção da operação, conforme o critério de gestão adotado.', 'Energia, manutenção, equipe e custos recorrentes de ocupação.', '', 'CAPEX, Fluxo de caixa', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — B3 — CAPEX e OPEX', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('EBITDA / LAJIDA', 'Earnings Before Interest, Taxes, Depreciation and Amortization', 'Finanças, custos e retorno', 'Resultado antes de juros, tributos sobre o lucro, depreciação e amortização. Não equivale ao caixa disponível.', 'Comparar desempenho operacional de unidades usando a mesma metodologia.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — CVM — Resolução 156', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('ROI', 'Return on Investment', 'Finanças, custos e retorno', 'Retorno sobre o investimento: relação entre resultado obtido e capital aplicado, com período e critério definidos.', 'Ganho líquido de R$ 20 mil sobre R$ 100 mil: ROI de 20%.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Payback', 'Prazo de recuperação', 'Finanças, custos e retorno', 'Tempo necessário para que os fluxos acumulados recuperem o investimento inicial; pode ser simples ou descontado.', 'Investimento de R$ 120 mil com retorno líquido constante de R$ 10 mil/mês: 12 meses no cálculo simples.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Fluxo de caixa', 'Entradas e saídas', 'Finanças, custos e retorno', 'Movimentação de dinheiro ao longo do tempo, utilizada para acompanhar liquidez e planejamento.', 'Registrar recebimentos, pagamentos e saldo projetado.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Capital de giro', 'Recursos da operação', 'Finanças, custos e retorno', 'Recursos necessários para sustentar o ciclo operacional, como estoque, recebíveis e pagamentos.', 'Reserva para manter a loja até receber suas vendas.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Margem de contribuição', 'Receita menos gastos variáveis', 'Finanças, custos e retorno', 'Valor que sobra da receita após custos e despesas variáveis, para cobrir gastos fixos e contribuir para o resultado.', 'Venda de R$ 100 com gastos variáveis de R$ 60 gera R$ 40.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Break-even', 'Ponto de equilíbrio', 'Finanças, custos e retorno', 'Nível de atividade em que as receitas cobrem os gastos considerados, sem lucro ou prejuízo no modelo.', 'Calcular quanto a loja precisa vender para cobrir seus gastos.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('DRE', 'Demonstração do Resultado do Exercício', 'Finanças, custos e retorno', 'Relatório que organiza receitas, custos, despesas e resultado de um período pelo regime de competência.', 'Analisar o resultado mensal de uma unidade.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Real Estate', 'Mercado imobiliário', 'Real Estate e operações imobiliárias', 'Atividades relacionadas a imóveis, como desenvolvimento, compra, venda, locação, gestão e investimento.', 'Prospecção de ativos para redes e investidores.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('BTS', 'Built to Suit', 'Real Estate e operações imobiliárias', 'No contexto de locação, imóvel adquirido, construído ou substancialmente reformado conforme necessidades do futuro ocupante.', 'Investidor entrega uma unidade adequada à operação de um supermercado.', '', 'CAPEX, Fit-out, Expansão de rede', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — Planalto — Lei 8.245/1991, art. 54-A', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Sale & leaseback', 'Venda com locação de retorno', 'Real Estate e operações imobiliárias', 'Operação em que o proprietário vende um imóvel e continua a ocupá-lo como locatário.', 'Rede vende sua loja a um investidor e permanece no local pagando aluguel.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('ABL', 'Área Bruta Locável', 'Real Estate e operações imobiliárias', 'Medida da área destinada à locação, conforme o padrão de medição adotado. Pode diferir da área construída total.', 'Comparar o tamanho locável de lojas e empreendimentos.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Cap rate', 'Capitalization Rate', 'Real Estate e operações imobiliárias', 'Relação entre receita operacional líquida anual do imóvel e seu valor ou preço, sob premissas definidas.', 'NOI de R$ 600 mil/ano e preço de R$ 10 milhões: 6% ao ano.', '', 'NOI, Valuation', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — JLL — Glossário de termos imobiliários', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('NOI', 'Net Operating Income', 'Real Estate e operações imobiliárias', 'Receita operacional do imóvel menos despesas operacionais atribuídas ao ativo, antes de financiamento e tributos sobre o lucro.', 'Apurar a renda do imóvel após custos operacionais do proprietário.', '', 'Cap rate, Vacância', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — JLL — Glossário de termos imobiliários', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Vacância', 'Espaço desocupado', 'Real Estate e operações imobiliárias', 'Parcela desocupada de um imóvel ou carteira; pode ser medida por área, unidades ou valor de receita potencial.', '200 m² vazios em 1.000 m² locáveis: vacância física de 20%.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026 — JLL — Glossário de termos imobiliários', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Retrofit', 'Atualização de edificação', 'Real Estate e operações imobiliárias', 'Intervenção para modernizar uma construção existente, melhorando sua funcionalidade e desempenho.', 'Atualizar instalações e adequar um prédio para novos usos.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('VGV', 'Valor Geral de Vendas', 'Real Estate e operações imobiliárias', 'Soma estimada dos preços de venda das unidades de um empreendimento. Não representa lucro.', 'Dez unidades estimadas em R$ 1 milhão cada: VGV de R$ 10 milhões.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Valuation', 'Avaliação de valor', 'Real Estate e operações imobiliárias', 'Processo de estimar o valor de uma empresa ou ativo utilizando metodologia e premissas específicas.', 'Avaliar um imóvel por comparáveis e geração de renda.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Locação direta', 'Modalidade de operação', 'Negociação e documentação comercial', 'Contratação da ocupação do imóvel por aluguel, sem a aquisição do ponto de um ocupante anterior.', 'Rede negocia o aluguel de uma loja disponível.', '', 'Carência, Proposta comercial, BTS', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Passagem de ponto comercial', 'Transferência negociada do ponto', 'Negociação e documentação comercial', 'Negócio envolvendo a posição comercial ou elementos de uma operação existente; o escopo deve ser definido.', 'Negociar instalações e posição comercial de uma loja em funcionamento.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Venda direta do ativo', 'Aquisição do imóvel', 'Negociação e documentação comercial', 'Compra e venda do próprio imóvel, com transferência conforme os instrumentos e registros aplicáveis.', 'Investidor adquire uma loja para sua carteira patrimonial.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('CDU / luvas', 'Cessão de Direito de Uso / expressão comercial', 'Negociação e documentação comercial', 'CDU é usada para cessão de direito de uso; luvas descrevem certos pagamentos de entrada. Não são equivalentes em todos os negócios.', 'Identificar objeto, beneficiário e condições antes de registrar o pagamento.', '', 'Passagem de ponto comercial, Locação direta', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Carência', 'Período de concessão', 'Negociação e documentação comercial', 'Prazo negociado de dispensa ou redução de determinada cobrança, com alcance definido no contrato.', 'Dois meses de carência do aluguel para implantação da loja.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('LOI', 'Letter of Intent', 'Negociação e documentação comercial', 'Carta de intenção que registra interesse e condições preliminares; seus efeitos dependem do texto e do contexto.', 'Apresentar parâmetros de aluguel e prazo para avaliação.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('NDA', 'Non-Disclosure Agreement', 'Negociação e documentação comercial', 'Acordo de confidencialidade que define condições de acesso, uso e proteção de informações.', 'Compartilhar dados de uma oportunidade sob confidencialidade.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Due diligence', 'Diligência de verificação', 'Negociação e documentação comercial', 'Análise organizada de informações e documentos para identificar condições e riscos de uma operação.', 'Verificar documentação, situação do imóvel e dados da negociação.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Proposta comercial', 'Oferta formal', 'Negociação e documentação comercial', 'Documento que apresenta objeto, valores, condições, prazos e demais parâmetros da negociação.', 'Proposta de locação com aluguel, garantia e carência.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Aditamento', 'Alteração de instrumento', 'Negociação e documentação comercial', 'Documento que modifica ou complementa condições de um contrato existente.', 'Ajustar prazo ou condições comerciais de uma locação.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Founder', 'Fundador ou fundadora', 'Gestão, cargos e sistemas', 'Pessoa que participa da criação de uma empresa. A grafia correta deste termo é Founder, não fander.', 'Fundador que criou e estruturou a empresa.', 'fander', 'Co-founder, CEO', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Co-founder', 'Cofundador ou cofundadora', 'Gestão, cargos e sistemas', 'Pessoa que funda uma empresa em conjunto com outra ou outras pessoas.', 'Dois profissionais criam uma empresa e são cofundadores.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('CEO', 'Chief Executive Officer', 'Gestão, cargos e sistemas', 'Principal executivo responsável pela condução geral da empresa, conforme sua estrutura de governança.', 'Executivo que coordena estratégia e direção do negócio.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('CFO', 'Chief Financial Officer', 'Gestão, cargos e sistemas', 'Executivo responsável pela área financeira, conforme a organização da empresa.', 'Responsável por orçamento, finanças e planejamento financeiro.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('COO', 'Chief Operating Officer', 'Gestão, cargos e sistemas', 'Executivo responsável pela condução das operações.', 'Responsável pela execução operacional e desempenho das unidades.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Head de expansão', 'Liderança da expansão', 'Gestão, cargos e sistemas', 'Profissional que coordena crescimento territorial, novas unidades e projetos de implantação.', 'Responsável por avaliar regiões e negociar novos pontos.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('KPI', 'Key Performance Indicator', 'Gestão, cargos e sistemas', 'Indicador escolhido para medir o desempenho de um objetivo relevante.', 'Número de contratos fechados ou prazo médio de negociação.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('ERP', 'Enterprise Resource Planning', 'Gestão, cargos e sistemas', 'Sistema integrado para gerir processos empresariais, como compras, estoque e financeiro.', 'Integrar estoque, faturamento e contas a pagar.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('BI', 'Business Intelligence', 'Gestão, cargos e sistemas', 'Métodos e ferramentas para transformar dados em informações úteis à decisão.', 'Painel de oportunidades por bairro, etapa e modalidade.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('SLA', 'Service Level Agreement', 'Gestão, cargos e sistemas', 'Acordo que define níveis de serviço, responsabilidades e critérios de atendimento.', 'Prazo combinado para entregar um estudo de mercado.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Ticket médio', 'Valor médio por venda', 'Indicadores e inteligência de mercado', 'Receita de vendas dividida pelo número de transações no mesmo período.', 'R$ 50 mil em 1.000 vendas: ticket médio de R$ 50.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Giro de estoque', 'Rotação do estoque', 'Indicadores e inteligência de mercado', 'Indicador de renovação do estoque; exige base consistente, como custo vendido dividido por estoque médio a custo.', 'Comparar a velocidade de saída de uma categoria de produtos.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Sell-in', 'Venda ao canal', 'Indicadores e inteligência de mercado', 'Venda do fabricante ou fornecedor ao distribuidor ou varejista.', 'Fornecedor entrega produtos para uma rede de lojas.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Sell-out', 'Venda ao consumidor', 'Indicadores e inteligência de mercado', 'Venda realizada pelo canal varejista ao consumidor final.', 'A loja comercializa os produtos recebidos do fornecedor.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('SSS', 'Same-Store Sales', 'Indicadores e inteligência de mercado', 'Comparação das vendas de lojas equivalentes em períodos comparáveis, conforme critérios definidos.', 'Comparar vendas das mesmas unidades entre dois anos.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Trade area', 'Área de influência', 'Indicadores e inteligência de mercado', 'Território de onde uma operação atrai ou tende a atrair seus clientes.', 'Estimar de quais bairros vêm os compradores de uma loja.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Isócrona', 'Área por tempo de acesso', 'Indicadores e inteligência de mercado', 'Delimitação dos locais alcançáveis em determinado tempo e modo de deslocamento.', 'Área a dez minutos de caminhada de um ponto comercial.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Geomarketing', 'Análise geográfica de mercado', 'Indicadores e inteligência de mercado', 'Uso de dados territoriais para orientar decisões de localização, venda e atendimento.', 'Cruzar renda, população, concorrentes e acesso na escolha do imóvel.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('SWOT', 'Strengths, Weaknesses, Opportunities and Threats', 'Indicadores e inteligência de mercado', 'Análise de forças, fraquezas, oportunidades e ameaças de um negócio ou projeto.', 'Identificar boa exposição, limitações do imóvel e concorrência.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "glossario_termos" ("termo", "nome_extenso", "categoria", "significado", "exemplo", "aliases", "relacionados", "fonte", "revisado_em") VALUES ('Footfall', 'Fluxo de visitantes', 'Indicadores e inteligência de mercado', 'Quantidade de pessoas que passam por um local ou entram nele, conforme a regra de medição.', 'Contar pedestres por faixa de horário em frente à loja.', '', '', 'Glossário Empresarial Prospecção Brasil, 30/09/2026', '2026-09-30');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Araruama', 'RJ', 'Centro / ruas comerciais', 42.0, 30.0, 60.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Bangu', 'Rio de Janeiro', 'Calçadão / Av. Cônego de Vasconcelos', 35.0, 25.0, 50.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Barra da Tijuca', 'Rio de Janeiro', 'Av. das Américas / eixos comerciais', 52.71, 40.0, 75.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Botafogo', 'Rio de Janeiro', 'Voluntários da Pátria / São Clemente', 89.65, 65.0, 120.0, 'A', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Bonsucesso', 'Rio de Janeiro', 'Teixeira de Castro / Cardoso de Morais', 30.0, 22.0, 45.0, 'C', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Cabo Frio', 'RJ', 'Centro / principais ruas comerciais', 54.0, 40.0, 75.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Campo Grande', 'Rio de Janeiro', 'Calçadão / Cel. Agostinho / Augusto de Vasconcelos', 35.48, 25.0, 50.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Catete', 'Rio de Janeiro', 'Rua do Catete', 65.0, 50.0, 90.0, 'A', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Caxias', 'Duque de Caxias', 'Rua José de Alvarenga / Calçadão', 240.0, 150.0, 350.0, 'Prime', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Copacabana', 'Rio de Janeiro', 'N. Sra. de Copacabana / Barata Ribeiro', 40.51, 35.0, 60.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Flamengo', 'Rio de Janeiro', 'Marquês de Abrantes / Senador Vergueiro', 75.0, 55.0, 100.0, 'A', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Gávea', 'Rio de Janeiro', 'Marquês de São Vicente', 90.0, 65.0, 120.0, 'A', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Grajaú', 'Rio de Janeiro', 'Barão de Mesquita / Eng. Richard', 45.0, 30.0, 60.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Humaitá', 'Rio de Janeiro', 'Rua Humaitá / Voluntários da Pátria', 85.0, 60.0, 115.0, 'A', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Ipanema', 'Rio de Janeiro', 'Visconde de Pirajá / Garcia D''Ávila', 157.78, 120.0, 200.0, 'Prime', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Itaguaí', 'RJ', 'Centro / Dr. Curvelo Cavalcanti', 35.0, 25.0, 50.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Jardim Botânico', 'Rio de Janeiro', 'Rua Jardim Botânico / Lopes Quintas', 90.0, 65.0, 125.0, 'A', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Leblon', 'Rio de Janeiro', 'Ataulfo de Paiva / Dias Ferreira', 265.93, 200.0, 350.0, 'Prime', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Largo do Machado', 'Rio de Janeiro', 'Largo do Machado / entorno Rua do Catete', 70.0, 50.0, 95.0, 'A', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Madureira', 'Rio de Janeiro', 'Calçadão / Min. Edgard Romero / Carolina Machado', 35.0, 25.0, 55.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Mesquita', 'RJ', 'Centro / Getúlio de Moura', 30.0, 20.0, 45.0, 'C', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Miguel Couto', 'Nova Iguaçu', 'Centro comercial local', 25.0, 18.0, 35.0, 'C', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Nilópolis', 'RJ', 'Centro / Rua Mirandela', 30.0, 22.0, 45.0, 'C', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Nova Iguaçu', 'RJ', 'Rua Governador Portela / Centro', 60.0, 45.0, 85.0, 'A', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Penha', 'Rio de Janeiro', 'Av. Braz de Pina / Rua Nicarágua', 35.0, 25.0, 50.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Piabetá', 'Magé', 'Centro / eixo comercial', 25.0, 18.0, 35.0, 'C', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Ramos', 'Rio de Janeiro', 'Rua Uranos / entorno Av. Brasil', 30.0, 22.0, 45.0, 'C', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Recreio dos Bandeirantes', 'Rio de Janeiro', 'Av. das Américas / Gláucio Gil / Benvindo de Novaes', 42.34, 32.0, 60.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Santa Cruz', 'Rio de Janeiro', 'Rua Felipe Cardoso / centro comercial', 40.0, 25.0, 60.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Santa Cruz da Serra', 'Duque de Caxias', 'Centro / principais eixos comerciais', 22.0, 15.0, 30.0, 'C', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('São Cristóvão', 'Rio de Janeiro', 'Rua São Cristóvão / Figueira de Melo', 40.0, 28.0, 55.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('São Pedro da Aldeia', 'RJ', 'Centro / vias comerciais', 50.0, 35.0, 70.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Tijuca', 'Rio de Janeiro', 'Conde de Bonfim / Barão de Mesquita / Saens Peña', 39.55, 30.0, 55.0, 'B', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
INSERT INTO "benchmarks_locacao" ("local", "municipio", "corredor", "valor_m2", "minimo_m2", "maximo_m2", "classe", "fonte") VALUES ('Urca', 'Rio de Janeiro', 'Av. Portugal / Marechal Cantuária', 70.0, 50.0, 100.0, 'A', 'Prospecção Brasil — Inteligência Imobiliária RJ (PDF fornecido por Luiz; data-base não informada)');
